 DROP TABLE IF EXISTS movies; DROP TABLE IF EXISTS genres;
CREATE TABLE genres (id SERIAL PRIMARY KEY, name VARCHAR(50));
CREATE TABLE movies ( id SERIAL PRIMARY KEY, title VARCHAR(100) NOT NULL, synopsis VARCHAR(100) NOT NULL, release_year INTEGER, trailer_url VARCHAR(100), genres_id INTEGER REFERENCES genres(id));
